#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PortableCongress
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class CommitteeList : PortableRazor.ViewBase
{

#line hidden

#line 2 "CommitteeList.cshtml"
public Committees Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<html>\n<head>\n\t<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"jquery.mobile-1.4.0.min.css\"");

WriteLiteral(" />\n\t<script");

WriteLiteral(" src=\"jquery-1.10.2.min.js\"");

WriteLiteral("></script>\n\t<script");

WriteLiteral(" src=\"jquery.mobile-1.4.0.min.js\"");

WriteLiteral("></script>\n</head>\n<body>\n\t<div");

WriteLiteral(" data-role=\"header\"");

WriteLiteral(" style=\"overflow:hidden;\"");

WriteLiteral(" data-position=\"fixed\"");

WriteLiteral(">\n");

WriteLiteral("\t\t");


#line 12 "CommitteeList.cshtml"
Write(Html.ActionLink("Back", "ShowPoliticianView", new {id = @Model.Id}, new { 
			@class="ui-btn-left ui-btn ui-icon-back ui-btn-icon-notext ui-shadow ui-corner-all",
			data_icon = "arrow-l", 
			data_role="button", 
			data_mini="true", 
			data_inline="true", 
			data_transition="slide"}));


#line default
#line hidden
WriteLiteral("\n    \t<h1>Committees</h1>\n    </div>\t\t\n\n\t<ul");

WriteLiteral(" data-role=\"listview\"");

WriteLiteral(" data-inset=\"true\"");

WriteLiteral(">\n");


#line 23 "CommitteeList.cshtml"
		

#line default
#line hidden

#line 23 "CommitteeList.cshtml"
   foreach(var committee in Model.CommitteeList) {


#line default
#line hidden
WriteLiteral("\t\t\t<li><h4>");


#line 24 "CommitteeList.cshtml"
      Write(committee.Name);


#line default
#line hidden
WriteLiteral("</h4></li>\n");


#line 25 "CommitteeList.cshtml"
		}


#line default
#line hidden
WriteLiteral("\t</ul>\n</body>\n</html>");

}
}
}
#pragma warning restore 1591
